### ISSUE TITLE
UI doesn't tell the user when the compute process dies

### ISSUE THREAD

**Issue by holyguster** [att/rcloud#1601]
The set of commands below, when run at the R prompt, causes a core dump with this message:

    (process:12785): GLib-GIO-ERROR **: Settings schema 'org.gnome.system.proxy' is not installed
    Trace/BPT trap(coredump)

When run in RCloud 1.4, the RCloud UI makes it look like that the code is running forever (cell execution spinning icon is shown).

Seems like the RCloud UI should detect this kind of error somehow, and let the user know.

Here are the commands:

```r
library(FSelector)
data(iris)
result = cfs(Species ~ ., iris)
```

**Comment by s-u** [comment]
Two issues here:

 - something odd happens when the subprocess dies, because the read pipe doesn't get the usual EOF signal and thus the control process has no idea that the compute process died. I have worked around that by having the control process check the compute process for death and signal accordingly.
- the UI ignores `compute_terminated` OOB, so even if the death is signaled, the UI doesn't show it. This is likely in part because we don't know what to do when the compute process dies since we can't really do much useful at that point ..

**Comment by gordonwoodhull** [comment]
I think the expected behavior would be to bring up an Aw Shucks "your compute session died" and offer to create a new one.

I didn't know about that OOB. I guess we don't have an API for creating just a new compute session. We would also need it if we want to implement SIGKILL (#1089).

As a stopgap, if the OOB works, we could do Aw Shucks and offer to reload the notebook. That's not as painfully slow as reloading the page, anyway.

**Comment by s-u** [comment]
Agreed. With Rserve 1.8-4 the OOB works - it's active on chusuk if you want to test.
BTW: there is a 5s timeout right now, but it could be shortened if we feel it's necessary.

**Comment by s-u** [comment]
BTW: much easier way to test is simply

```r
q("no")
```

**Comment by gordonwoodhull** [comment]
Ha. I like that test.

I'll see if I can get to this for 1.4.3 (in August)

**Comment by s-u** [comment]
(FWIW Rserve 1.8-4 is now also on tupile since it also fixes the more grave but related #1605)

**Comment by anatoliyg** [comment]
when you quit a process, we see the "shucks" message, therefore the issue is fixed

**Comment by gordonwoodhull** [comment]
I think @anatoliyg must have tested this on an instance without compute separation. It still happens.
