### ISSUE TITLE
discover page thumbnails are piling up

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2024]
I don't think this happened before #2014, although I don't see what changes there would have caused it. Seems like it is assuming all images are the same height, and a short height.

![image](https://cloud.githubusercontent.com/assets/1366709/15810156/db74b71c-2b69-11e6-8577-c2b06e3c4b21.png)

**Comment by gordonwoodhull** [comment]
My guess is that this is an initialization order problem. If you click to Popular and back to Recent, the heights are drawn correctly.

**Comment by paulinshek** [comment]
I think it's because the missing.png is added after .imagesLoaded() is called.

**Comment by gordonwoodhull** [comment]
Fixed in #2051

**Comment by Prateek032** [comment]
On latest commit a3cace2, I am able to reproduce this on Firefox browser

**Comment by gordonwoodhull** [comment]
There may still be a race condition since we don't know when the browser will fire `onerror`. And in fact I don't think we need onerror since we should know if we got a thumbnail or not by the result of `get_thumb`.

**Comment by gordonwoodhull** [comment]
fixed in #2065

**Comment by amithrb** [comment]
This issue still persists, I am able to reproduce this on Firefox browser on commit 71d7f6c

**Comment by gordonwoodhull** [comment]
Hopefully #2094 has fixed this. 

I'm not able to repro on Linux/Windows/OSX x Chrome/Firefox. However, that doesn't mean there still isn't some kind of platform problem here.

I don't think we can blame global latency because we don't hit GitHub at all in the Discover page now; all data should be coming from local RCS now.

I'm going to assume that µ∑ is still seeing this, but put it off to an Unknown release because none of the devs are able to repro.

**Comment by shaneporter** [comment]
I _was_ able to reproduce, albeit quite infrequently. It now _seems_ to be working. Or at least, I am not able to reproduce using the method I used before. (Try and try again.)

**Comment by gordonwoodhull** [comment]
Okay, let's close this yet again!
