### ISSUE TITLE
wdcplot error

### ISSUE THREAD

**Issue by rhknag** [att/rcloud#904]
I've seen this failure often with large data sets.  Does it really indicate out of memory or something else?

```
Exception creating dcplot definition: unexpected section -
```

**Comment by gordonwoodhull** [comment]
Hi @rhknag, we recently debugged some errors due to large messages.  It looks like your notebook is fixed now - please check!

**Comment by rhknag** [comment]
I still get
Error fetching contents from notebook 'fa5801f26e197c046c5b', version ''
Error in doTryCatch(return(expr), name, parentenv, handler): File `null' not found in notebook `fa5801f26e197c046c5b'

**Comment by rhknag** [comment]
Oh – nevermind.  Your recent fix was for my old wdcplot error I see.
I’ll have to see if I can recreate it

Ralph

From: KNAG, RALPH H (RALPH H)
Sent: Thursday, February 05, 2015 10:14 AM
To: 'att/rcloud'
Cc: 'Gordon Woodhull'
Subject: RE: [rcloud] wdcplot error (#904)

I still get
Error fetching contents from notebook 'fa5801f26e197c046c5b', version ''
Error in doTryCatch(return(expr), name, parentenv, handler): File `null' not found in notebook `fa5801f26e197c046c5b'

**Comment by gordonwoodhull** [comment]
Right, notebook.R is still broken but wdcplot looks more stable to me with large data sets. As noted above, rserve.js was failing in some cases on large messages, which are fixed now.

**Comment by rhknag** [comment]
I see I provided a test above.  I ran this successfully both on the current RCloud and RCloud 5

Incidentally I think the problem I had with wdcplot hanging yesterday may have been caused by local memory.   I did see it again today, but when I killed a few large programs it worked.
